version: '3'
services:
    server:
        build: 
            dockerfile: dockerfile
            context: ./server 
        env_file:
            - ./.env
        ports:
            - '8000:8000'
        volumes:
            - /app/node_modules 
            - ./server:/app
    nginx:
        restart: always
        build: 
            dockerfile: dockerfile
        env_file:
            - ./.env
        ports: 
            - '80:80' 
        volumes:
            - /app/node_modules 
            - ./server:/app